services:
  facilitator:
    build: .
    image: "docker.io/ptrusr/trustless-x402-facilitator@sha256:5e2dc33dc466206ca792502c9808b6a87d784cd466216a3afc55fcd6de5f34fc"
    platform: linux/amd64
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock # appd REST API for ROFL KMS
    ports:
      - "8080:8080"
    annotations:
      net.oasis.proxy.ports.8080.custom_domain: x402.updev.si
    environment:
      - SIGNER_TYPE=private-key
      - RPC_URL_BASE_SEPOLIA=https://sepolia.base.org
      - RPC_URL_SOLANA_DEVNET=https://api.devnet.solana.com
